### ISSUE TITLE
Add an OSS license

### ISSUE THREAD

**Issue by cameronfletcher** [TracklessTrolley/TrolleyBus#16]
This repository doesn't contain any license information and the code doesn't have any license information in it either. If this is an OSS projects it makes sense to include a OSS license.

Here are some links that may help with the process of choosing an including a license:  
- http://choosealicense.com/
- http://stackoverflow.com/questions/20243214/how-to-change-the-license-for-a-project-at-github

**Comment by martaciesielska** [comment]
There was a license file in the repo. :) But I've renamed it and made some slight changes.
